### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by caoyangs** [electrode-io/electrode-react-ssr-caching#4]
https://github.com/electrode-io/electrode-react-ssr-caching/search?utf8=%E2%9C%93&q=gen-lib

```
module.js:457
    throw err;
    ^
Error: Cannot find module '../gen-lib/render-greeting'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/electrode-io/electrode-react-ssr-caching/test/spec/caching.simple.spec.js:6:61)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/mocha/lib/mocha.js:485:10)
    at Object.<anonymous> (/home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module.runMain (module.js:590:10)
    at runFn (/home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/async/lib/async.js:52:16
    at /home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/async/lib/async.js:361:13
    at /home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/async/lib/async.js:52:16
    at done (/home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/async/lib/async.js:246:17)
    at /home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/async/lib/async.js:44:16
    at /home/travis/build/electrode-io/electrode-react-ssr-caching/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1739:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jchip** [comment]
`npm test` works fine.
