### ISSUE TITLE
Simple cache test failing

### ISSUE THREAD

**Issue by danielstocks** [electrode-io/electrode-react-ssr-caching#6]
After failing to even get a simple "demo" working, I'm starting to wonder if I've missed something really basic. Does this only run within the context of electrode or something?

My test code:

``` js
import SSRCaching from "electrode-react-ssr-caching";
import { renderToString } from "react-dom/server";
import React, {Component} from "react";

const cacheConfig = {
  components: {
    "Hello": {
      strategy: "simple",
      enable: true
    }
  }
}
SSRCaching.enableCaching();
SSRCaching.enableCachingDebug();
SSRCaching.setCachingConfig(cacheConfig);


class Hello extends Component {
  render() {
    return <div>Hello, {this.props.name}</div>
  }
}

renderToString(<Hello name="Daniel" />);
```

Babel config:

``` .babelrc
{ "presets": ["es2015", "react"] }
```

Package.json

``` json
{
  "dependencies": {
    "electrode-react-ssr-caching": "^0.1.3",
    "react": "15.3.0",
    "react-dom": "15.3.0"
  },
  "devDependencies": {
    "babel-cli": "^6.16.0",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-react": "^6.16.0"
  }
}
```

When running index.js i get the following error:

```
TypeError: Cannot assign to read only property 'props' of #<Object>
    at mountComponentCache (/Users/daniel/Projects/test-ssr-caching/node_modules/electrode-react-ssr-caching/lib/ssr-caching.js:304:26)
    at Object.ReactReconciler.mountComponent (/Users/daniel/Projects/test-ssr-caching/node_modules/react/lib/ReactReconciler.js:47:35)
    at /Users/daniel/Projects/test-ssr-caching/node_modules/react/lib/ReactServerRendering.js:46:36
    at ReactServerRenderingTransaction.Mixin.perform (/Users/daniel/Projects/test-ssr-caching/node_modules/react/lib/Transaction.js:138:20)
    at renderToStringImpl (/Users/daniel/Projects/test-ssr-caching/node_modules/react/lib/ReactServerRendering.js:44:24)
    at renderToString (/Users/daniel/Projects/test-ssr-caching/node_modules/react/lib/ReactServerRendering.js:73:10)
    at Object.<anonymous> (/Users/daniel/Projects/test-ssr-caching/out/index.js:70:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

Any clue as to why this wouldn't work?

I cloned this repo and succesfully ran `npm test`, so I have no idea what's going on here.

**Comment by danielstocks** [comment]
I figured it out.

In the tests you are har coding `process.env.NODE_ENV = "production";`

In development React won't allow to update object props.

Will create PR to update README so other people don't fall in the same trap.
